In [6]:
import numpy as np
# 类型转换
random_data = np.random.randint(0,2,size=10)
float_data = random_data.astype(np.bool_)
float_data.dtype

dtype('bool')

In [7]:
float_data

array([False,  True, False,  True, False,  True, False,  True,  True,
       False])

In [9]:
array2 = np.random.randint(4,100,size=(5,8))
array2

array([[51, 97, 74, 64, 99, 74, 66, 17],
       [18, 55, 52, 39, 56, 42, 99, 72],
       [58, 17, 71, 59, 36, 58,  7, 73],
       [76, 41, 85, 29, 57, 36, 58, 34],
       [74, 82, 90, 11, 52,  7,  6, 32]])

In [13]:
# 访问第一行
array2[[0]]

array([[51, 97, 74, 64, 99, 74, 66, 17]])

In [ ]:
juq 429