In [13]:
import numpy as np
import pandas as pd
array = np.random.randint(1,100,size=(5,6))
array

array([[65, 85, 99, 30,  5, 55],
       [26, 25,  7, 84, 81, 72],
       [91, 82, 42,  4, 23,  2],
       [57, 82, 97, 19, 73, 80],
       [70, 53,  4, 85, 69, 41]])

In [10]:
array.sum(axis=1)

array([322, 272, 214, 313, 454])

In [11]:
array.sum(axis=0)

array([259, 317, 346, 131, 264, 258])

In [15]:
pd.DataFrame(array.sum(axis=1))

0
0  339
1  295
2  244
3  408
4  322

In [33]:
# any and or import!!!
python = np.random.randint(0, 100, size=100)
python

array([18,  9, 60, 13, 46, 92, 53, 41, 28, 23, 96, 21, 37,  1,  3, 97,  2,
       43, 89, 90,  6, 77, 22,  9, 55, 86, 35, 55, 52, 93, 80, 92, 59, 30,
        0, 31,  4, 54, 24, 87,  7, 88, 35, 90, 22, 26, 45, 91, 89, 99, 79,
       61, 92, 51, 94, 19, 56, 23, 64, 61, 58, 78, 12, 76, 34, 52, 51, 37,
       77, 31, 94, 27, 60, 56, 73,  6, 88, 32,  7, 44, 42, 76, 81, 64, 21,
       90, 78, 98, 99, 77, 80,  5,  5, 31, 18, 23, 92, 74, 37, 30])

In [23]:
python < 60

array([False,  True, False, False, False,  True,  True, False,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True, False,  True, False, False,  True,  True,
        True,  True, False,  True, False, False,  True, False,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
       False,  True,  True, False, False,  True, False,  True,  True,
       False, False,  True, False, False,  True,  True,  True, False,
       False,  True, False, False,  True, False, False, False,  True,
       False])

In [24]:
python[python < 60]

array([ 3, 45, 28, 21, 31, 56, 37, 37, 23,  7, 25, 47, 50, 15, 50,  6, 19,
       29, 49, 36, 37,  9, 50, 56, 11, 48, 41, 59, 13, 15, 54, 47, 35, 30,
        2, 20,  3, 33, 12, 16, 35, 20, 28, 38, 10, 36, 16, 26,  1, 34, 26,
       40,  1, 24, 42,  5, 17, 47, 22,  1, 18,  6])

In [34]:
(python == 100).any()

False

In [35]:
(python != 100).all()

True

In [36]:
score = np.random.randint(0,100,size=(10,3))
score

array([[47, 61, 86],
       [29, 45, 41],
       [63, 51, 53],
       [54, 75, 48],
       [96, 63, 53],
       [22, 91, 76],
       [56, 41,  4],
       [99, 26, 14],
       [67, 29,  9],
       [57, 98, 40]])

In [37]:
# 查找超过90的，至少一门，查找至少有一门学科超过90的同学
score[(score > 90).any(axis=1)]


array([[96, 63, 53],
       [22, 91, 76],
       [99, 26, 14],
       [57, 98, 40]])

In [41]:
data = np.random.randint(0,100,size=(5,3))
data = data.astype(np.float64)
data[0,1] = np.nan
data

array([[59., nan, 22.],
       [39., 39., 82.],
       [41., 47., 74.],
       [35., 28., 18.],
       [16., 12., 45.]])

In [44]:
 # 排序
np.sort(data,axis=0)

array([[16., 12., 18.],
       [35., 28., 22.],
       [39., 39., 45.],
       [41., 47., 74.],
       [59., nan, 82.]])

In [49]:
# 部分排序,得到最小的两个数,partition(a,k)k为负值就是得到最大的数
np.partition(data,2,axis=0)

array([[16., 12., 18.],
       [35., 28., 22.],
       [39., 39., 45.],
       [41., 47., 82.],
       [59., nan, 74.]])