In [21]:
import numpy as np
import pandas as pd
#设置小数位数3位
np.set_printoptions(precision=3)
array = np.random.randint(1,100,size=(7,6))
array

array([[ 5, 14, 43, 66, 36,  2],
       [11, 49,  3, 92, 69, 32],
       [98, 34, 18, 73, 47, 49],
       [10,  6, 58, 93, 11, 91],
       [41, 81, 90, 17, 80, 18],
       [46, 21, 39, 13, 36, 71],
       [33, 48, 20, 13, 63, 27]])

In [22]:
array.sum(axis=0)

array([244, 253, 271, 367, 342, 290])

In [36]:
np.around(array.mean(axis=1),3)

array([27.667, 42.667, 53.167, 44.833, 54.5  , 37.667, 34.   ])

In [24]:
array.sum(axis=0)

array([244, 253, 271, 367, 342, 290])

In [25]:
pd.DataFrame(array.sum(axis=1))

0
0  166
1  256
2  319
3  269
4  327
5  226
6  204

In [26]:
# any and or import!!!
python = np.random.randint(0, 100, size=100)
python

array([54, 88, 23, 59, 67, 48, 42, 31, 21, 97, 10, 51, 67, 13, 79, 35, 79,
       61, 80, 89, 47, 39, 23, 36, 51, 65, 90, 90, 88, 13,  4, 86, 88, 36,
       57, 34, 13, 76, 46, 71, 53, 25, 20, 51, 28, 60, 43, 67, 74, 12, 80,
        3, 66, 36, 62, 36, 35,  2, 66, 49, 73, 46, 18, 89, 18, 44, 25, 82,
       18, 85, 89, 70, 42, 32, 42, 29, 18, 10, 77, 60, 96, 46, 69, 25,  5,
       74, 41, 19, 76,  5, 17, 94, 20, 74, 19, 90, 60,  6, 14, 83])

In [27]:
python < 60

array([ True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True, False, False,
       False, False,  True,  True,  True,  True,  True, False, False,
       False, False,  True,  True, False, False,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
       False,  True, False, False,  True, False,  True, False,  True,
       False,  True,  True,  True, False,  True, False,  True,  True,
       False,  True,  True,  True, False,  True, False, False, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True, False,  True,  True, False,  True,  True, False,  True,
        True, False,  True, False,  True, False, False,  True,  True,
       False])

In [28]:
python[python < 60]

array([54, 23, 59, 48, 42, 31, 21, 10, 51, 13, 35, 47, 39, 23, 36, 51, 13,
        4, 36, 57, 34, 13, 46, 53, 25, 20, 51, 28, 43, 12,  3, 36, 36, 35,
        2, 49, 46, 18, 18, 44, 25, 18, 42, 32, 42, 29, 18, 10, 46, 25,  5,
       41, 19,  5, 17, 20, 19,  6, 14])

In [29]:
(python == 100).any()

False

In [30]:
(python != 100).all()

True

In [31]:
score = np.random.randint(0,100,size=(10,3))
score

array([[96, 62, 83],
       [39,  6, 64],
       [61, 21,  3],
       [41, 68, 27],
       [25, 17, 44],
       [27,  3, 20],
       [72, 74, 44],
       [31, 85, 87],
       [29, 64, 30],
       [15, 53, 37]])

In [32]:
# 查找超过90的，至少一门，查找至少有一门学科超过90的同学
score[(score > 90).any(axis=1)]


array([[96, 62, 83]])

In [33]:
data = np.random.randint(0,100,size=(5,3))
data = data.astype(np.float64)
data[0,1] = np.nan
data

array([[86., nan, 51.],
       [73., 79., 66.],
       [53., 43., 86.],
       [75., 63., 57.],
       [12., 95., 19.]])

In [34]:
 # 排序
np.sort(data,axis=0)

array([[12., 43., 19.],
       [53., 63., 51.],
       [73., 79., 57.],
       [75., 95., 66.],
       [86., nan, 86.]])

In [35]:
# 部分排序,得到最小的两个数,partition(a,k)k为负值就是得到最大的数
np.partition(data,2,axis=0)

array([[12., 43., 19.],
       [53., 63., 51.],
       [73., 79., 57.],
       [75., nan, 86.],
       [86., 95., 66.]])