In [3]:
import numpy as np

In [4]:
# 创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1
array = np.zeros(10)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
# 创建一个元素从10到49的ndarray对象
array = np.random.randint(10,49,size=1)
array

array([11])

In [14]:
# 创建一个10*10的对象，并打印出最大最小元素
array = np.random.random(size=(10,10))
array.max()

0.9917207822310293

In [15]:
# 创建一个10*10的对象，并打印出最大最小元素
array = np.random.random(size=(10,10))
array.min()

0.013874804305627597

In [4]:
# 将第二题所有元素翻转,使用切片，这个不会啊？
array = np.zeros(10)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [36]:
# 如何根据第3列来对一个5*5的矩阵排序
array1 = np.random.randint(0,100,size=(5,5))
array1

array([[76, 17,  7, 48,  8],
       [24, 76, 70, 18, 35],
       [35, 59, 81, 28, 50],
       [50, 19, 21, 28,  5],
       [79, 44, 38, 81, 40]])

In [39]:
# 先获取第三列的数值
col_2 = array1[:,2]
col_2

array([ 7, 70, 81, 21, 38])

In [41]:
# 给第三列排序
sort_values = np.sort(array1[:,2])
sort_values

array([ 7, 21, 38, 70, 81])

In [48]:
#  获取排序后的的在原始值中的索引,加个[0,0]就可以只要数字
new_index = []
for x in sort_values:
    index = np.argwhere(col_2 == x)[0,0]
    new_index.append(index)
    print(index)

0
3
4
1
2


In [47]:
# 排序，按新序列访问,即为按第三列数据排序
array1[new_index]

array([[76, 17,  7, 48,  8],
       [50, 19, 21, 28,  5],
       [79, 44, 38, 81, 40],
       [24, 76, 70, 18, 35],
       [35, 59, 81, 28, 50]])

In [49]:
# 一个跟简单的自带函数
array1[np.argsort(array1[:,2])]

array([[76, 17,  7, 48,  8],
       [50, 19, 21, 28,  5],
       [79, 44, 38, 81, 40],
       [24, 76, 70, 18, 35],
       [35, 59, 81, 28, 50]])